# First stage of Dockerfile
FROM adoptopenjdk/openjdk8:alpine-jre

# ARGS
ARG BUNDLER_VERSION=2.0.2
ARG GRADLE_VERSION=6.1.1
ARG KOTLIN_VERSION=1.3.61
ARG ANDROID_COMMAND_LINE_TOOLS_VERSION=6609375
ARG BUILD_TOOLS="29.0.3"
ARG TARGET_SDK="29"

# ENVS
ENV GRADLE_HOME /gradle-${GRADLE_VERSION}
ENV KOTLIN_HOME /kotlinc
ENV ANDROID_HOME /opt/android-sdk-linux/tools
ENV PATH $PATH:${GRADLE_HOME}/bin:${KOTLIN_HOME}/bin:${ANDROID_HOME}/bin:/build-tools/${BUILD_TOOLS}

COPY . /src

RUN apk add build-base bash curl wget sudo

# download and install Android SDK
# https://developer.android.com/studio#command-tools
RUN wget -q https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_COMMAND_LINE_TOOLS_VERSION}_latest.zip && \
    unzip *tools*linux*.zip
# We CAN NOT have tools in the root of the unit, this is why it is inside cmd-linetools
RUN mkdir -p opt/android-sdk-linux && mv tools opt/android-sdk-linux/tools

# ENV SDKMANAGER_OPTS="--add-modules java.se.ee"

RUN set -xe \
    && mkdir -p ~/.android ~/.gradle \
    && touch ~/.android/repositories.cfg \
    && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties \
    && yes | sdkmanager --licenses 1>/dev/null

RUN sdkmanager --update --verbose
# Install SDK Packages
# RUN sdkmanager "build-tools;${BUILD_TOOLS}" "platforms;android-${TARGET_SDK}"

# # Accept Android licenses
# RUN yes | $ANDROID_HOME/bin/sdkmanager --licenses

# Install Firebase CLI
RUN curl -Lo ./firebase_bin https://firebase.tools/bin/linux/latest
RUN mv firebase_bin firebase && chmod 700 firebase

# install gradle
RUN curl https://downloads.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip >> gradle.zip && \
    unzip gradle.zip;

# download and install Kotlin compiler
# https://github.com/JetBrains/kotlin/releases/latest
RUN wget https://github.com/JetBrains/kotlin/releases/download/v${KOTLIN_VERSION}/kotlin-compiler-${KOTLIN_VERSION}.zip && \
    unzip *kotlin*.zip

# Second stage of Dockerfile
FROM alpine:latest  

# ARGS
ARG GRADLE_VERSION=6.1.1
ARG BUILD_TOOLS="29.0.3"
ARG TARGET_SDK="29"

ENV GRADLE_HOME /gradle-${GRADLE_VERSION}
ENV KOTLIN_HOME /kotlinc
ENV ANDROID_HOME /opt/android-sdk-linux/tools
ENV PATH $PATH:${GRADLE_HOME}/bin:${KOTLIN_HOME}/bin:${ANDROID_HOME}/bin:/build-tools/${BUILD_TOOLS}

# Copy Firebase
COPY --from=0 /firebase /usr/bin/firebase
# Copy Gradle
COPY --from=0 ${GRADLE_HOME} ${GRADLE_HOME}
# Copy Kotlin
COPY --from=0 ${KOTLIN_HOME} ${KOTLIN_HOME}
# Copy Android Command Tools
COPY --from=0 ${ANDROID_HOME} ${ANDROID_HOME}