name: CI-Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: syncmoney/android:latest
        build-args: SDK_TOOLS=6609375, BUILD_TOOLS=29.0.2, ANDROID_API=29

    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: syncmoney/android-slim:latest
        build-args: SLIM=1, SDK_TOOLS=6609375, BUILD_TOOLS=29.0.2, ANDROID_API=29